const prompts = [
    'Una playa desierta al atardecer',
    'Un bosque encantado en pleno invierno',
    'Un castillo en las nubes',
    'Una ciudad futurista bajo la lluvia',
    'Un barco pirata en alta mar',
    'Un jardín de flores luminosas',
    'Una montaña cubierta de nieve eterna',
    'Un mundo submarino lleno de criaturas coloridas',
    'Una cabaña solitaria en medio del bosque',
    'Un paisaje urbano surrealista con edificios flotantes',
    'Un campo de girasoles bajo un cielo azul',
    'Un puente antiguo rodeado de vegetación exuberante',
    'Un desierto con dunas interminables',
    'Un jardín zen con un estanque de nenúfares',
    'Una cueva misteriosa iluminada por cristales brillantes',
    'Una cascada gigante en un valle oculto',
    'Un pueblo medieval en el centro de la colina',
    'Un paisaje lunar con montañas de rocas afiladas',
    'Una ciudad sumergida en las profundidades del océano',
    'Un templo antiguo rodeado de niebla',
    'Un faro solitario en un acantilado escarpado',
    'Un mercado animado en una ciudad oriental',
    'Un acuario gigante lleno de peces exóticos',
    'Un jardín botánico con plantas gigantes',
    'Un parque de diversiones abandonado en la noche',
    'Un campo de tulipanes en todas las tonalidades',
    'Un volcán en erupción iluminando el horizonte',
    'Un puente colgante sobre un abismo profundo',
    'Un paisaje alienígena con criaturas extraterrestres',
    'Un reloj antiguo en una ciudad fantasma',
    'Un río serpenteante rodeado de árboles centenarios',
    'Un palacio flotante en el cielo',
    'Un bosque encantado lleno de hadas y duendes',
    'Un arco iris doble sobre un campo de flores',
    'Un paisaje helado con pingüinos jugando',
    'Un santuario antiguo oculto en una montaña',
    'Un cementerio embrujado en la noche de luna llena',
    'Un parque temático en el espacio exterior',
    'Un puente de cristal suspendido sobre un cañón profundo',
    'Un paisaje surrealista con árboles multicolores',
    'Un castillo encantado rodeado de niebla espesa',
    'Un campo de lavanda bajo un cielo estrellado',
    'Una ciudad sumergida en la vegetación tropical',
    'Un lago tranquilo con cisnes blancos nadando',
    'Un castillo de arena en la playa',
    'Un paisaje urbano con rascacielos de cristal',
    'Un bosque encantado iluminado por luciérnagas',
    'Una cabaña acogedora en medio de la montaña',
    'Un acantilado rocoso con olas rompiendo en la orilla',
    'Un cielo nocturno lleno de estrellas brillantes',
    'Una pradera cubierta de margaritas',
    'Un puente de piedra antiguo sobre un río sereno',
    'Una isla tropical con palmeras y aguas cristalinas',
    'Un bosque encantado con árboles bioluminiscentes',
    'Una ciudad futurista con vehículos voladores',
    'Un lago sereno rodeado de montañas majestuosas',
    'Una cueva submarina con vida marina vibrante',
    'Un paisaje nevado con una cabaña acogedora',
    'Un campo de amapolas bajo un cielo naranja',
    'Un puente colgante en medio de un desfiladero profundo',
    'Una cascada impresionante rodeada de exuberante vegetación',
    'Un pueblo costero pintoresco con casas de colores',
    'Un paisaje urbano caótico con rascacielos futuristas',
    'Un bosque encantado con hadas danzantes',
    'Un campo de lavanda morada en plena floración',
    'Un jardín japonés con un estanque de carpas koi',
    'Una montaña imponente con picos nevados',
    'Una playa paradisíaca con aguas turquesas y arena blanca',
    'Un castillo medieval rodeado de un foso de agua',
    'Un cielo lleno de globos aerostáticos de colores',
    'Un oasis en medio del desierto con palmeras y agua cristalina',
];

export default prompts;
